### ISSUE TITLE
他社の混雑状況サービスのリサーチ

### ISSUE THREAD

**Issue by BERRY-YT** [selebseed/congestion_mapping#7]
他社で既にある混雑状況サービスのリサーチをする。

**Comment by BERRY-YT** [comment]
◆トクバイ
チラシのサービスサイト。5月頭からコロナの影響で、スーパーやドラックストアなどの混雑状況を過去のデータから表示している。リアルタイムでの混雑状況もあるが、そちらは店側が手動で３段階で設定する。東京などの都会では、対応しているが山口など地方では未対応。

・トクバイのサイト
https://tokubai.co.jp/%E3%82%A4%E3%83%88%E3%83%BC%E3%83%A8%E3%83%BC%E3%82%AB%E3%83%89%E3%83%BC/8999

・トクバイのサービスの説明
https://www.itmedia.co.jp/business/articles/2005/11/news091.html

<img width="1280" alt="スクリーンショット 2020-05-16 11 10 04" src="https://user-images.githubusercontent.com/62860280/82106674-d50b4c80-9765-11ea-88cd-fb7d63fa757a.png">


◆お買い物混雑マップ(https://covid19.unerry.jp/)
お買物混雑マップでは直近4週間の中で最も混雑している1時間あたりの人数を基準とし、時間帯ごとに「いつもより空いている」「通常程度」「通常より混雑」に分類される。掲載店舗エリア数は5月7日時点で28,367件。

・参考サイト
https://robotstart.info/2020/05/08/unerry-shopping-map.html

<img width="1280" alt="スクリーンショット 2020-05-16 11 05 53" src="https://user-images.githubusercontent.com/62860280/82106621-8f4e8400-9765-11ea-83ad-b5b303f9e961.png">

◆その他
・VACAN https://www.forval-iot.jp/column/news-08/
カメラセンサーやAIを利用しリアルタイムで表示。

店が自社のサービスを持っていることもある。
・ローソン
https://lawsonkonzatsu.blob.core.windows.net/view/index.html?utm_source=app&utm_medium=app&utm_term=&utm_content=pickup&utm_campaign=20200501-konzatsu

**Comment by selebseed** [comment]
@BERRY-YT これってAPI提供してるかとか調べた？
